/** Declaration file generated by dts-gen */
declare module "pug-error" {
    export = error;

    interface ErrorOptions {
        filename?: string;
        line?: number;
        column?: number;
        src?: string;
    }

    function error(code: string, message: string, options: ErrorOptions): any;
}
